export const REQUIRED_V2_INSTRUCTIONS = [
  "create_contract",
  "add_milestone",
  "finalize_terms",
  "accept_contract",
  "decline_contract",
  "expire_acceptance",
  "expire_activation",
  "approve_activation",
  "reject_activation",
  "submit_trial_work",
  "request_trial_revision",
  "approve_trial_and_activate",
  "settle_trial_and_end",
  "submit_work_unit",
  "request_revision",
  "void_stale_revision",
  "approve_work_unit",
  "finalize_review_timeout",
  "release_stream_accrual",
  "cancel_active_contract",
  "withdraw_freelancer",
  "claim_employer_refund",
  "open_dispute",
  "resolve_dispute",
  "complete_contract",
  "create_hourly_contract",
  "start_hourly_session",
  "stop_hourly_session",
  "end_hourly_contract",
] as const;

export type RequiredV2Instruction = (typeof REQUIRED_V2_INSTRUCTIONS)[number];
